
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - ./:/app
      - ./db.sqlite3:/app/db.sqlite3  # Monta el archivo SQLite como volumen
      - /etc/localtime:/etc/localtime:ro  # Sincroniza la hora
      - /etc/timezone:/etc/timezone:ro    # Sincroniza la zona horaria
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - UID=${UID}
      - GID=${GID}
    command: /bin/bash -c "chown ${UID}:${GID} /app/db.sqlite3 && chmod 664 /app/db.sqlite3 && python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - django
    command: /bin/bash -c "chmod -R 755 /app/staticfiles && chown -R www-data:www-data /app/staticfiles && nginx -g 'daemon off;'"