# Generated by Django 5.1.3 on 2025-01-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("cliente", models.CharField(max_length=255)),
                ("documento", models.CharField(max_length=20)),
                ("fecha", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prestacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("descripcion", models.TextField(max_length=150)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "honorarios",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ayudante",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gastos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "anestesia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("servicio", models.CharField(max_length=50)),
                ("practica", models.CharField(max_length=150)),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestaciones",
                        to="facturacion.presupuesto",
                    ),
                ),
            ],
        ),
    ]
