# Generated by Django 5.1.3 on 2025-01-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0002_presupuesto_prestacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestacion",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="prestacion",
            name="presupuesto",
        ),
        migrations.CreateModel(
            name="DetallePrestacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "prestacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturacion.prestacion",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestaciones",
                        to="facturacion.presupuesto",
                    ),
                ),
            ],
        ),
    ]
