# Generated by Django 5.1.3 on 2025-01-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0003_remove_prestacion_cantidad_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalleprestacion",
            name="cantidad",
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturacion.presupuesto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detalleprestacion",
            name="item",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="facturacion.item",
            ),
            preserve_default=False,
        ),
    ]
